#!/bin/bash
set -e

DIR=/data/entrypoint.d

if [[ -d "$DIR" ]]
then
  	for SCRIPT in /data/entrypoint.d/*
	do
		if [ -f $SCRIPT -a -x $SCRIPT ]
		then
            echo "Running script: $SCRIPT";
			$SCRIPT;
			RESULT="$?";
			if [ $RESULT != 0 ]; then
                echo "Error : $RESULT when executing before script: $SCRIPT"
                exit RESULT
            fi
		fi
	done
fi

echo "Starting application"
exec "$@"